### PR TITLE
Added arm64 support

### PR DESCRIPTION
**Pull request by movie0125**
Added arm64 support

### CODE REVIEW

**Comment by kokes** [comment]
I think this (and all other platform/os combos) could be solved by moving to x/sys/unix - see my issue https://github.com/tobert/pcstat/issues/26

For reference, the relevant constant for linux/arm64 is defined here - https://cs.opensource.google/go/x/sys/+/master:unix/zsysnum_linux_arm64.go;l=263?q=SYS_SETNS&ss=go%2Fx%2Fsys

**Comment by movie0125** [comment]
@kokes 
You're right, please open your PR

**Comment by kokes** [comment]
@movie0125 see #30

**Comment by movie0125** [comment]
@kokes Tks

**Comment by tobert** [comment]
Hey, sorry for the delay on these PRs. I merged #30 and some other updates, and everything seems fine on ARM now.

**Pull request closed without merging**
